name: Feature Request
description: Suggest a new feature or enhancement for expo-drawing
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) should this feature target?
      options:
        - iOS only
        - Android only
        - Both iOS and Android
        - Platform-agnostic (JavaScript/TypeScript)
      multiple: false
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Motivation
      description: Why do you need this feature? What problem does it solve?
      placeholder: |
        I'm building a note-taking app and need to...
        This would help by...
    validations:
      required: true

  - type: textarea
    id: proposed-api
    attributes:
      label: Proposed API (Optional)
      description: If you have ideas about how the API should look, share them here
      render: typescript
      placeholder: |
        <DrawingView
          strokeStyle="dotted"
          onStrokePressure={(event) => console.log(event.pressure)}
        />

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe alternatives you've considered...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
      multiple: false
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or references about the feature request here

  - type: checkboxes
    id: contribute
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a PR to implement this feature
          required: false

